spring:
  cloud:
    config:
      username: "administrator"
      password: "Bilge123!!"
      uri: "http://192.168.1.28:8888"
  config:
    import: "configserver:"
  application:
    name: auth-service
