apiVersion: v1
kind: Secret
metadata:
  name: bilge-social-secrets
type: Opaque
stringData:
   auth_service_port: "8091"
   auth_service_spring_rabbit_host: "34.118.80.59"
   auth_service_spring_rabbit_port: "5672"
   auth_service_spring_rabbit_username: "BilgeAdamAdmin"
   auth_service_spring_rabbit_password: "BilgeAdam!**"
   auth_service_datasource_url: "jdbc:postgresql://34.118.80.59:5432/AuthDb"
   auth_service_datasource_username: "postgres"
   auth_service_datasource_password: "BilgeAdam!**"
   auth_service_zipkin_baseurl: "http://34.118.80.59:9411"
   auth_service_myapplication_userservice: "localhost:8090"

   elastic_service_server_port: "7777"
   elastic_service_spring_rabbit_host: "34.118.80.59"
   elastic_service_spring_elastic_uri: "34.118.80.59:9200"
   elastic_service_spring_rabbit_port: "5672"
   elastic_service_spring_rabbit_username: "BilgeAdamAdmin"
   elastic_service_spring_rabbit_password: "BilgeAdam!**"

   user_service_port: "8090"
   user_service_spring_rabbit_host: "34.118.80.59"
   user_service_spring_rabbit_port: "5672"
   user_service_spring_rabbit_username: "BilgeAdamAdmin"
   user_service_spring_rabbit_password: "BilgeAdam!**"
   user_service_data_mongodb_database: "socialmedia"
   user_service_data_mongodb_username: "bilgeadamuser"
   user_service_data_mongodb_password: "!b1lgeadam**"
   user_service_data_mongodb_host: "34.118.80.59"
   user_service_data_mongodb_port: "27017"
   user_service_zipkin_baseurl: "http://34.118.80.59:9411/"

   web_service_server_port: "80"
   web_service_zipkin_baseurl: "http://34.118.80.59:9411/"

   api_gateway_service_server_port: "3333"
   api_gateway_service_zipkin_baseurl: "http://34.118.80.59:9411/"

   config_service_zipkin_baseurl: "http://34.118.80.59:9411/"

   config_security_username: "administrator"
   config_security_password: "Bilge123!!"
   config_security_url: "http://localhost:8888"

   token_security_key_sign: "A7dfdtnSmjKDpQxwjtAfljaYkNPJFZ9bIJAG08pq4c77kXPvvE"

   GOOGLE_APPLICATION_CREDENTIALS: "googlekey.json"
