server:
  port: 8091

spring:
  rabbitmq:
    host: 34.118.80.59
    port: 5672
    username: authservice
    password: 123456
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.116.249.119:5432/AuthDb
    username: postgres
    password: BilgeAdam!**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true
  zipkin:
    enabled: true
    base-url: http://34.118.92.201:9411/
    service-name: auth-service

myapplication:
  userservice: 192.168.1.2:8090

logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: authservice.log