server:
  port: ${auth_service_port}

spring:
  rabbitmq:
    host: ${auth_service_spring_rabbit_host}
    port: ${auth_service_spring_rabbit_port}
    username: BilgeAdamAdmin
    password: BilgeAdam!**
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.118.92.201:5432/AuthDb
    username: postgres
    password: BilgeAdam!**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true
  zipkin:
    enabled: true
    base-url: http://34.118.92.201:9411/
    service-name: auth-service

myapplication:
  userservice: 192.168.1.28:8090

logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: authservice.log