server:
  port: 8090

spring:
  rabbitmq:
    host: 34.118.92.201
    port: 5672
    username: BilgeAdamAdmin
    password: BilgeAdam!**
  data:
    mongodb:
      database: socialmedia
      username: bilgeadamuser
      password: '!b1lgeadam**'
      host: 34.116.167.132
      port: 27017
  zipkin:
    enabled: true
    base-url: http://34.118.92.201:9411/
    service-name: user-service

logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: userservice.log