server:
  port: 80

spring:
  zipkin:
    enabled: true
    base-url: http://34.118.92.201:9411/
    service-name: web-service

s3:
  accesskey: ${AWS_ACCESSKEY_S3}
  secretkey: ${AWS_SECRETKEY_S3}


logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: webservice.log