server:
  port: 8888

spring:
  security:
    user:
      name: administrator
      password: Bilge123!!
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services
  zipkin:
    enabled: true
    base-url: http://34.118.92.201:9411/
    service-name: config-server

logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  ##  com.bilgeadam.controller: debug
  file:
    name: configserver.log
    ## path: \\server\\logs\\configserver\\