server:
  port: 8888

spring:
  security:
    user:
      name: administrator
      password: Bilge123!!
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services